version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      # - POSTGRES_USER_FILE=/run/secrets/postgres_user
      # - POSTGRES_DB=omero
      # - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero-network
    volumes:
      - "omero-db:/var/lib/postgresql/data"
    secrets:
      - postgres_user
      - postgres_password

  omeroserver:
    image: "openmicroscopy/omero-server:5.6"
    # env_file:
    #   - ./secrets/.env.omeroserver
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero-network
    ports:
      - 4063:4063
      - 4064:4064
    volumes:
      - "omero-server:/OMERO"

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5.14"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero-network

networks:
  omero-network:

volumes:
  omero-db:
  omero-server:

secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  omero_root_password:
    file: ./secrets/omero_root_password